# -*- coding: utf-8 -*-
"""Python_Basico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ffF_KMGi6o2vTUxqAfQO_X7HeDOYu4d7

#AULA 1

# Atividade 1 - Operadores
"""

x=((6+7)*9)
print(x)

x=6+4*2
print(x)

x=(4*9+5)
print(x)

x=(15+20-30)
print(x)

x=(6+5**2)
print(x)

"""# Atividade 2 - Atribuição"""

x=8
x+=5
print(x)
x=8
x-=4
print(x)
x=8
x*=20
print(x)
x=8
x/=2
print(x)

x=8
x+=5
x-=4
x*=20
x/=2
print(x)

"""# Atividade 3 - Comparação"""

x=8
x1=3
result1=x<x1
result2=x==x1
result3=x>=x1
result4=x!=x1
print(result1,"\n", result2,"\n", result3, "\n", result4,"\n")

"""# Atividade 4 - Operadores de identidade"""

x1="botafogo"
x2="flamengo"
x3="botafogo"
result1= x1 is x3
result2= x1 is not x2
result3= x1 is x2
result4= x2 is not x3
print(result1,"\n", result2,"\n", result3, "\n", result4,"\n")

"""# Atividade 5 - Operadores de associação"""

frutas=("banana", "laranja", "uva", "ameixa")
x1="banana"
x2="laranja"
x3="abacaxi"
result1= x1 in frutas
result2= x1 not in frutas
result3= x2 not in frutas
result4= x3 in frutas
print(result1,"\n", result2,"\n", result3, "\n", result4,"\n") #TESTEprint(f'Resultado 1:{x_result1}`)